language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t testecx14/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true testecx14/docker-react npm run test